#!/usr/bin/python

from usbtmc import usbtmc

"""
Scan the AOTF drive frequency of the given channel through the given band,
recording the power from a Thorlabs PM100 power meter at every frequency
"""

presets = {           # (chan, min_f, max_f, wavelength)
        'green':        (1, 68.5, 70.5, 514),
        'red':          (2, 51.5, 55.5, 647),
}

def plot(data):
        from matplotlib import pyplot as pl
        freqs = np.unique(data['f'])
        powers = [ data[data['f'] == f]['p'] for f in freqs ]
        means = [ np.mean(p) for p in powers ]
        stds = [ np.std(p) for p in powers ]

        pl.errorbar(x=freqs, y=means, yerr=stds, fmt='.')
        pl.xlabel('Frequency (MHz)')
        pl.ylabel('Relative transmitted power')

        max_i = np.argmax(abs(data['p']))
        m = data[max_i]
        pl.axvline(x=m['f'])
        pl.figtext(0.6, 0.8, 'Maximum: %2.3f MHz' % m['f'])

        pl.show()

if __name__ == '__main__':
        import sys, time
        import numpy as np
        from gooch_housego import FreqSynth
        import argparse

        parser = argparse.ArgumentParser()
        parser.add_argument('-p', '--plot', action='store_true', help='plot power vs. frequency')
        parser.add_argument('-o', '--output', type=argparse.FileType('w'), help='output raw data to file')
        parser.add_argument('-s', '--step', type=float, metavar='FREQ', help='scan step size in MHz', default=0.010)
        parser.add_argument('-P', '--preset', metavar='NAME', choices=presets.keys(),
                        help='select a preset scan configuration (options: %s)' % ', '.join(presets.keys()))
        parser.add_argument('-l', '--lower', type=float, metavar='FREQ', help='beginning of scan in MHz')
        parser.add_argument('-b', '--upper', type=float, metavar='FREQ', help='end of scan in MHz')
        parser.add_argument('-c', '--channel', type=int, metavar='N', help='AOTF driver channel to scan')
        parser.add_argument('-W', '--wavelength', type=float, metavar='N', help='Wavelength of line to measure (nm)')
        parser.add_argument('-w', '--wait', type=float, metavar='TIME', help='duration to wait between data points', default=1e-3)
        parser.add_argument('-S', '--samples', type=int, metavar='N', help='number of samples to take for each frequency', default=5)
        args = parser.parse_args()

        channel = args.channel
        lower = args.lower
        upper = args.upper
        wavelength = args.wavelength

        if args.preset is None:
                pass
        elif args.preset in presets:
                channel,lower,upper,wavelength = presets[args.preset]
        else:
                parser.error("Unknown preset configuration '%s'" % args.preset)

        if channel is None or lower is None or upper is None:
                parser.error("Need at least channel, lower and upper frequencies")

        test = usbtmc('/dev/usbtmc0')
        test.write('CONF:POW')
        
        if wavelength is not None:
                test.write('SENSE:CORR:WAVELENGTH MIN %f' % (wavelength-5))
                test.write('SENSE:CORR:WAVELENGTH MAX %f' % (wavelength+5))

        synth = FreqSynth.probe()
        for ch in range(8):
                synth.select_channel(ch)
                synth.set_mode('off')
        synth.select_channel(channel)
        synth.set_mode('on')
        synth.set_amplitude(1023)

        data = []
        for freq in np.arange(lower, upper, args.step):
                synth.set_frequency(freq)
                time.sleep(args.wait)
                for i in range(args.samples):
                        test.write('READ?')
                        val = float(test.read())
                        data.append((freq, val))

        data = np.array(data, dtype=[('f', 'f8'), ('p', 'f8')])

        max_i = np.argmax(abs(data['p']))
        print 'Maximum at %3.3f MHz' % data['f'][max_i]
        synth.set_frequency(data[max_i]['f'])

        if args.output is not None:
                args.output.write('# Time (seconds)\tPower (Watts)\n')
                np.savetxt(args.output, data, '%3.5e')

        if args.plot:
                plot(data)

