#!/usr/bin/python

from time import sleep, time
from thorlabs_pm100 import ThorlabsPM100

meter = ThorlabsPM100.find()
while True:
        val = meter.read()
        print time(), '\t', val
        sleep(10e-3)

