#!/usr/bin/python

from time import sleep, time
from usbtmc import usbtmc

test = usbtmc('/dev/usbtmc0')
test.write('CONF:POW')
        
while True:
        test.write('READ?')
        val = float(test.read())
        print time(), '\t', val
        sleep(10e-3)

